# Create these secrets in Google Cloud Secret Manager before deploying.
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trvelle
spec:
  template:
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/trvelle-463918/custom-fastapi/trvelle:latest
        ports:
          containerPort: 8001
        env:
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: trvelle-tavily-api-key
              key: latest
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: trvelle-google-api-key
              key: latest
        - name: SERPAPI_API_KEY
          valueFrom:
            secretKeyRef:
              name: trvelle-serpapi-api-key
              key: latest
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: trvelle-db-uri
              key: latest
        - name: DEBUG
          value: 'False'
